name: CI
on: [push, pull_request]
jobs:

  qmake:
    name: "qmake on ${{ matrix.image }}"
    runs-on: ubuntu-22.04
    container:
      image: "${{ matrix.image }}"
    strategy:
      matrix:
        include:
          - {image: "ubuntu:18.04", qt: "qt5-default"}
          - {image: "ubuntu:20.04", qt: "qt5-default"}
          - {image: "ubuntu:22.04", qt: "qtbase5-dev"}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Install qt and build tools
        run: |
          apt-get update &&
          apt-get install -y --no-install-recommends \
            pkg-config g++ make \
            ${{ matrix.qt }} qttools5-dev-tools
      - name: Run qmake
        run: qmake -r "QMAKE_CXXFLAGS=-std=c++11 -Werror"
      - name: Build
        run: make -j8

  cmake:
    name: "cmake on ${{ matrix.image }}"
    runs-on: ubuntu-22.04
    container:
      image: "${{ matrix.image }}"
    strategy:
      matrix:
        include:
          - {image: "ubuntu:18.04", qt: "qt5-default"}
          - {image: "ubuntu:20.04", qt: "qt5-default"}
          - {image: "ubuntu:22.04", qt: "qtbase5-dev"}
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Install qt and build tools
        run: |
          apt-get update &&
          apt-get install -y --no-install-recommends \
            pkg-config g++ make cmake \
            ${{ matrix.qt }} qttools5-dev-tools
      - name: Show cmake version
        run: cmake --version
      - name: Run cmake
        run: cmake -S .
      - name: Build
        run: VERBOSE=1 cmake --build .
